### ISSUE TITLE
The starcounter-include is not aware about visible property

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-include#8]
The `starcounter-include` is not aware about `visible` property which makes it impossible to use with Launcher.

**Comment by miyconst** [comment]
cc @warpech

**Comment by warpech** [comment]
Is it an enhancement proposal or a regression?

**Comment by miyconst** [comment]
My bad. I thought `visible` is an attribute of `launcher-include`.

It is just css:

``` css
starcounter-include.workspace {
    display: none;
}

starcounter-include.workspace[visible] {
    display: block;
}
```

Do you think it's better to add a css class instead?
