### ISSUE TITLE
Shadow DOM (ShadyCSS) styles do not work in polyfilled browsers

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#85]
It was reported in https://github.com/Starcounter/starcounter-include/issues/82 that Shadow DOM styles **bleed** in the polyfilled browsers.

The problem turns out to be much bigger - CSS is not shimmed at all in polyfilled browsers.

See (Firefox on the left, Chrome on the right): 

![image](https://user-images.githubusercontent.com/566463/35522216-05ec416c-051c-11e8-9c33-409679ce031b.png)

Source code for the above demo: https://github.com/Starcounter/starcounter-include/blob/9d4e0fe5c39b4a318c6b519a8f1e49b05bc3d366/demo/partial.html#L10-L19

@tomalec what can be done about this?

Without it, Uniform.css does not work in `declarative-shadow-dom` in browsers other than Chrome.

**Comment by tomalec** [comment]
That was also reported in #82
> 👎 the shadow DOM scoping is broken in others as well as even though markup is prepared for scoping, styles are not - I'm still trying to find a way to use limited ShadyCSS API to make it work,

It is so, because ShadyCSS polyfill does not translate CSS text, so far there is no API to do that for non-template content (composition fetched from DB) and for non-custom-element host. What is worse, since we are using `@import` we would not be able to translate it either way.

I would wait with full-blown solution for upcoming refactoring of ShadyCSS.

If we need something fast, I'd provide fallback selectors manually in `uniform.css`.
So, to make `.wrap-my-button>::slotted(button)` work in polyfilled browsers, we need to add `starcounter-include .style-scope.starcounter-include.wrap-my-button>button`
- It still may not work in some border cases (as found in #82), when polyfill fails to add `.style-scope` cleasses that limits the bleeding.
   In such case, we could fallback to leakier `.wrap-my-button>button`
- It may occur that polyfilled browser fails to read entire composed selector if one part is unrecognizable.
   Then instead of 
   ```css
   .wrap-my-button>::slotted(button),
   starcounter-include .style-scope.starcounter-include.wrap-my-button>button{
       color: green;
   }
   ```
   we will have to write
   ```css
   .wrap-my-button>::slotted(button){
       color: green;
   }
   starcounter-include .style-scope.starcounter-include.wrap-my-button>button{
       color: green;
   }
   ```
   In such case, we will definitely need a pre-processor for that.
- `starcounter-include .style-scope.starcounter-include.wrap-my-button>button` does not cover the use of `uniform.css` in shadow root of different (custom) element
   We could either,
   - Fall back to leaky `.wrap-my-button>button`, or
   - Ask users to translate for themselves.
